### ISSUE TITLE
Supervisor not configured correctly

### ISSUE THREAD

**Issue by bkrahmer** [TheKatastrophe/vmail-postfix-dovecot-opendkim#1]
Hi.  I'm not sure if you tested this configuration, but it didn't work at all for me.  Supervisor was complaining because the services detach.  Here is a diff from my working configuration.  thanks.

diff --git a/conf/supervisord.conf b/conf/supervisord.conf
index 9a8d3e8..91a2ee6 100644
--- a/conf/supervisord.conf
+++ b/conf/supervisord.conf
@@ -22,7 +22,7 @@ supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
 serverurl=unix:///tmp/supervisor.sock ; use a unix:// URL  for a unix socket

 [program:opendkim]
-command=/sbin/opendkim -x /etc/opendkim.conf
+command=/sbin/opendkim -f -x /etc/opendkim.conf
 autostart=true
 autorestart=true
 priority=5
@@ -32,7 +32,7 @@ stderr_logfile=/dev/stderr
 stderr_logfile_maxbytes=0

 [program:dovecot]
-command=/sbin/dovecot -c /etc/dovecot/dovecot.conf
+command=/sbin/dovecot -F -c /etc/dovecot/dovecot.conf
 autostart=true
 autorestart=true
 priority=10
@@ -43,10 +43,11 @@ stderr_logfile_maxbytes=0

 [program:postfix]
 command=/sbin/postfix -c /etc/postfix start
-autostart=true
-autorestart=true
+startsecs=0
+autorestart=false
 priority=15
 stdout_logfile=/dev/stdout
 stdout_logfile_maxbytes=0
 stderr_logfile=/dev/stderr
 stderr_logfile_maxbytes=0

**Comment by echoesactiii** [comment]
Hi,

Thanks for getting in touch. I've since revised this container not to use supervisord - it wasn't my intention to use it in the first place necessarily, but I wanted to give it a try and see if it did what I wanted. Ultimately I've now removed supervisord from the image.

Thanks though!

**Comment by bkrahmer** [comment]
It wasn't a bad idea, but it was my bad for assuming that the image was working.  i also had major problems getting your configuration of dovecot working too.  i basically started from scratch with the postfix and dovecot configurations, but got it working in the end.  at least i learned more about docker :)

**Comment by echoesactiii** [comment]
If you let me know what trouble you had with dovecot/postfix configs, that may be helpful. I've got it working as-is in the current configuration in production in a few places, but if it needs to be more flexible for others, that's a thing I'd like to accomodate if I can! :)
